### ISSUE TITLE
Add argument to from_sql for SELECT query

### ISSUE THREAD

**Issue by jpmckinney** [wireservice/agate-sql#14]
So that csvsql and sql2csv can use it.

**Comment by onyxfish** [comment]
So there was a good reason I didn't do this and now I don't remember what it was. Something to do with the way the queries are structured in sqlalchemy was blocking me. But yes, it is essential if we're migrating `csvsql` to this.

**Comment by onyxfish** [comment]
Superseded by `from_sql_query` though this still turns out to be impractical for csvkit and I've stuck with the existing code there.
