### ISSUE TITLE
how to install agate and agatesql in cloud foundry

### ISSUE THREAD

**Issue by rajrohith** [wireservice/agate-sql#27]
Hi Team,
when i try to install agate and agate-sql from python-buildpack which is not able to install and getting error
"2017-08-06T13:21:48.42-0500 [STG/0] ERR   Could not find a version that satisfies the requirement agatesql (from versions: )
   2017-08-06T13:21:48.48-0500 [STG/0] ERR No matching distribution found for agatesql
   2017-08-06T13:21:48.50-0500 [STG/0] ERR CondaValueError: Value error: pip returned an error."

please guide me how to install in my cloud foundry.

I appreciate you help in this regards

Thanks,
Raj

**Comment by jpmckinney** [comment]
http://agate-sql.readthedocs.io/en/0.5.2/#install

`pip install agate-sql`

Seems like you ran `pip install agatesql` instead.
