### ISSUE TITLE
MSSQL dialect uses BOOLEAN instead of BIT

### ISSUE THREAD

**Issue by franksiler** [wireservice/agate-sql#31]
Looking at the code, I'm wondering if this is actually an SQLAlchemy issue, but if I use any of the `csvkit` commands with `-i mssql`, I get back out `BOOLEAN` instead of `BIT` and have to replace before running in MSSQL.  Appreciate any tips.

**Comment by jpmckinney** [comment]
https://github.com/wireservice/csvkit/issues/1015
