### ISSUE TITLE
0.6.0 is tagged to wrong commit

### ISSUE THREAD

**Issue by s-t-e-v-e-n-k** [wireservice/agate-sql#41]
059b687c11e83b824b53be70214e3e269dfd11a7 is the sha1 that changes the version to 0.6.0, but the 0.6.0 tag is on 98c5817b1cc8c15d75e59279f62a30383cf1b45a, which titled "chore: flake8"

**Comment by jpmckinney** [comment]
Ah, thanks! I also just realized this repo isn’t configured for auto-PyPI releases.

**Comment by jpmckinney** [comment]
Tag is deleted - will tag correctly on release.
